<?php
// Database Settings
define('DB_DSN', 'mysql:host=127.0.0.1;dbname=ursh;port=3306');
define('DB_USER', 'root');
define('DB_PASSWORD', 'bakanakoto123');
//Global Settings
define('Debug', 'false'); // For Development (It currently does nothing) 
define('Host','https://localhost'); // For link preveiw, does not affect core functionality
define('generateLinkLength','6'); //How long should the Autogenerated link be?

?>